"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SocialLinks from "../components/SocialLinks";

const fallbackProjects = [
  { name: "EduNexa", type: "Full Stack", desc: "An advanced learning platform with courses, dashboards, quizzes and smart learning workflows.", tech: "Next.js · TypeScript · Node.js · MySQL", image: "/anime/project-sunset.jpg", github: "https://github.com/", demo: "#" },
  { name: "Online Shopping System", type: "Web", desc: "A responsive e-commerce experience focused on product discovery and clean customer workflows.", tech: "PHP · MySQL · Bootstrap", image: "/anime/project-city.jpg", github: "https://github.com/", demo: "#" },
  { name: "AI Chat Assistant", type: "AI/ML", desc: "A conversational assistant concept with an elegant interface and extensible AI architecture.", tech: "Python · AI · APIs", image: "/anime/project-ai.jpg", github: "https://github.com/", demo: "#" }
];
const skills=["C++","Python","JavaScript","TypeScript","React","Next.js","Node.js","Express","PHP","MongoDB","MySQL","Git"];
const fallback={github:"https://github.com/",linkedin:"https://linkedin.com/",instagram:"https://instagram.com/",email:"your-email@example.com",whatsapp:"https://wa.me/"};

export default function Home(){
 const [profile,setProfile]=useState(fallback); const [projects,setProjects]=useState(fallbackProjects); const [active,setActive]=useState("All"); const [copied,setCopied]=useState(false); const [menu,setMenu]=useState(false);
 useEffect(()=>{try{const p=localStorage.getItem("vt_profile");if(p)setProfile({...fallback,...JSON.parse(p)});const q=localStorage.getItem("vt_projects");if(q)setProjects(JSON.parse(q));}catch{}}
 ,[]);
 const filtered=useMemo(()=>active==="All"?projects:projects.filter((p:any)=>p.type===active),[active,projects]);
 const copy=async()=>{try{await navigator.clipboard.writeText(profile.email);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 return <main>
  <div className="ambient ambientOne"/><div className="ambient ambientTwo"/>
  <aside className="sideRail"><div className="railLogo">V<span>T</span></div><div className="railLine"/><div className="railSocial"><a href={profile.github} target="_blank">GH</a><a href={profile.linkedin} target="_blank">in</a><a href={profile.instagram} target="_blank">ig</a></div><div className="railText">BUILD · LEARN · CREATE</div></aside>
  <nav className="nav"><Link href="#top" className="brand"><span>V</span>ishwanath</Link><div className={menu?"links open":"links"}><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#skills" onClick={()=>setMenu(false)}>Skills</a><a href="#projects" onClick={()=>setMenu(false)}>Projects</a><a href="#experience" onClick={()=>setMenu(false)}>Experience</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></div><div className="navActions"><button className="round" aria-label="search">⌕</button><button className="themePill">✦ <span>ANIME MODE</span></button><Link className="adminBtn" href="/login">▣ Admin Login</Link><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></div></nav>

  <section className="hero" id="top"><div className="heroCopy"><div className="welcomeBadge">✦ WELCOME TO MY WORLD</div><h1>Vishwanath <span>Thakur</span></h1><h2>ASPIRING SOFTWARE ENGINEER <i>|</i> FULL STACK DEVELOPER <i>|</i> PROBLEM SOLVER</h2><div className="typeLine">I’m a <b>Software Developer</b><span className="cursor">|</span></div><p>Computer Science student passionate about building scalable software, solving complex problems, and creating meaningful digital experiences.</p><div className="heroButtons"><a className="primary glow" href="#projects">View My Projects →</a><a className="secondary" href="#contact">✉ Contact Me</a><a className="secondary" href="#resume">↓ Download Resume</a></div><div className="availability"> <span>●</span> Available for Internships & Opportunities <b>⌄</b></div></div><div className="heroArt"><div className="artGlow"/><img src="/anime/hero-anime.jpg" alt="Anime-inspired developer artwork"/><div className="quote">“Better<br/><b>Code.</b><br/>Brighter<br/><b>Future.</b>”</div><div className="jp">夢を追え</div></div></section>

  <section className="statBar"><Stat n="50+" t="Projects Completed" icon="▣"/><Stat n="300+" t="Problems Solved" icon="⌁"/><Stat n="15+" t="Technologies Used" icon="◇"/><Stat n="500+" t="GitHub Contributions" icon="◈"/></section>

  <section className="section split" id="about"><div className="sectionTag">01 · ABOUT ME</div><div className="splitGrid"><div className="animeCard"><img src="/anime/about-anime.jpg" alt="Anime-inspired profile artwork"/><div className="animeCaption">“A small step every day<br/>leads to big results.”</div></div><div><h2>More Than Just a <span>Student.</span></h2><p>I’m a Computer Science student who loves turning ideas into real-world projects. I enjoy coding, exploring new technologies, and constantly learning.</p><p>My goal is to build impactful solutions and grow into a strong software engineer.</p><a className="textLink" href="#contact">Know More About Me →</a></div></div></section>

  <section className="section" id="skills"><div className="sectionTag">02 · SKILLS</div><div className="sectionTitle"><h2>Technologies I <span>Work With</span></h2><a href="#projects">View All →</a></div><div className="skillsGrid">{skills.map((s,i)=><div className="skillCard" key={s}><div className="skillIcon">{["C++","Py","JS","TS","⚛","N","JS","Ex","PHP","◉","SQL","Git"][i]}</div><b>{s}</b><small>0{i+1}</small></div>)}</div></section>

  <section className="section" id="projects"><div className="sectionTag">03 · FEATURED PROJECTS</div><div className="sectionTitle"><h2>Things I’ve <span>Built.</span></h2><p>Each project is a step toward a bigger dream.</p></div><div className="filters">{["All","Full Stack","AI/ML","Web","DSA"].map(x=><button className={active===x?"active":""} key={x} onClick={()=>setActive(x)}>{x}</button>)}</div><div className="projectGrid">{filtered.map((p:any,i)=><article className="projectCard" key={p.name}><div className="projectImage"><img src={p.image||"/anime/project-city.jpg"} alt=""/><span>{p.type}</span><a href={p.github} target="_blank">↗</a></div><div className="projectBody"><small>0{i+1}</small><h3>{p.name}</h3><p>{p.desc}</p><div className="tech">{p.tech}</div><div className="projectLinks"><a href={p.github} target="_blank">GitHub ↗</a>{p.demo!=="#"&&<a href={p.demo} target="_blank">Live Demo ↗</a>}</div></div></article>)}</div></section>

  <section className="section journey" id="experience"><div className="sectionTag">04 · JOURNEY</div><div className="sectionTitle"><h2>Learning. Building. <span>Growing.</span></h2></div><div className="timeline"><div><b>2026 — Now</b><h3>Building Full Stack Products</h3><p>Working on EduNexa, portfolio systems and practical web applications.</p></div><div><b>2025 — 2026</b><h3>DSA & Software Foundations</h3><p>Strengthening C++, algorithms, databases and software development fundamentals.</p></div><div><b>Next Chapter</b><h3>Internships & Open Source</h3><p>Looking to collaborate, contribute and learn from real engineering teams.</p></div></div></section>

  <section className="section contact" id="contact"><div className="sectionTag">05 · LET’S CONNECT</div><div className="contactGrid"><div><h2>Let’s build something <span>great.</span></h2><p>Have an internship opportunity, project idea or collaboration in mind?</p><div className="socials"><a href={profile.github} target="_blank">GitHub ↗</a><a href={profile.linkedin} target="_blank">LinkedIn ↗</a><a href={profile.instagram} target="_blank">Instagram ↗</a><button onClick={copy}>✉ {copied?"Copied!":profile.email}</button></div></div><form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);window.location.href=`mailto:${profile.email}?subject=${encodeURIComponent(String(f.get("subject")))}&body=${encodeURIComponent(String(f.get("message")))}`}}><input name="name" required placeholder="Your name"/><input name="email" required type="email" placeholder="Your email"/><input name="subject" required placeholder="Subject"/><textarea name="message" required rows={5} placeholder="Tell me about your idea..."/><button className="primary glow">Send Message →</button></form></div></section>
  <footer><div><b>VT<span>.</span> Vishwanath Thakur</b><small>Building software · Solving problems · Learning continuously</small></div><SocialLinks/><span>© 2026</span></footer>
 </main>
}
function Stat({n,t,icon}:{n:string;t:string;icon:string}){return <div className="stat"><div className="statIcon">{icon}</div><div><b>{n}</b><small>{t}</small></div></div>}
